load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "sync_manager",
    hdrs = ["sync_manager.h", "sync_binding_prefs.pb.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "sync_binding_prefs_cc_proto",
    hdrs = ["sync_binding_prefs.pb.h"],
    visibility = ["//visibility:public"],
)
