#include "style.h"

#include <gtk/gtk.h>

static const char QS_CSS[] =
    "@keyframes qs-fade-in {"
    "  from { opacity: 0; }"
    "  to   { opacity: 1; }"
    "}"
    "@keyframes qs-float {"
    "  0% { transform: translateY(0px); }"
    "  50% { transform: translateY(-10px); }"
    "  100% { transform: translateY(0px); }"
    "}"
    "@keyframes qs-pulse-border {"
    "  0% { border-color: alpha(@window_fg_color, 0.1); }"
    "  50% { border-color: @accent_color; }"
    "  100% { border-color: alpha(@window_fg_color, 0.1); }"
    "}"
    ".qs-home-layout {"
    "  background-color: @window_bg_color;"
    "}"
    ".qs-home-left {"
    "  background-color: alpha(@window_fg_color, 0.02);"
    "}"
    ".qs-status-dot {"
    "  min-width: 8px;"
    "  min-height: 8px;"
    "  border-radius: 99px;"
    "  margin-right: 8px;"
    "}"
    ".qs-status-dot.online { background-color: #2ec27e; }"
    ".qs-status-dot.offline { background-color: alpha(@window_fg_color, 0.3); }"
    ".qs-status-toggle {"
    "  background: transparent;"
    "  border-radius: 8px;"
    "  padding: 6px 10px;"
    "  min-height: 0;"
    "  transition: background-color 150ms ease;"
    "}"
    ".qs-status-toggle:hover {"
    "  background-color: alpha(@window_fg_color, 0.06);"
    "}"
    ".qs-status-toggle:active {"
    "  background-color: alpha(@window_fg_color, 0.10);"
    "}"
    ".qs-status-chevron {"
    "  transition: transform 150ms ease;"
    "}"
    ".qs-status-toggle:hover .qs-status-chevron {"
    "  transform: translateX(2px);"
    "}"
    ".qs-link-button {"
    "  color: @accent_color;"
    "  font-weight: 700;"
    "  padding: 0;"
    "}"
    ".qs-drop-zone {"
    "  border: 2px dashed alpha(@window_fg_color, 0.1);"
    "  border-radius: 54px;"
    "  padding: 60px;"
    "  background-color: alpha(@window_fg_color, 0.01);"
    "  transition: all 400ms cubic-bezier(0.25, 0.46, 0.45, 0.94);"
    "}"
    ".qs-drop-zone:hover {"
    "  border-color: @accent_color;"
    "  background-color: alpha(@accent_color, 0.05);"
    "  transform: scale(1.02);"
    "}"
    ".qs-logo-float {"
    "  animation: qs-float 4s infinite ease-in-out;"
    "}"
    ".qs-splash-container {"
    "  animation: qs-fade-in 600ms ease-out;"
    "  padding: 48px;"
    "}"
    ".qs-splash-icon {"
    "  margin-bottom: 8px;"
    "}"
    ".qs-splash-loader {"
    "  margin-top: 32px;"
    "}"
    ".qs-hero-icon {"
    "  margin-top: 8px;"
    "  margin-bottom: 12px;"
    "  color: alpha(@window_fg_color, 0.7);"
    "}"
    ".qs-hero-block {"
    "  margin-bottom: 12px;"
    "  padding: 32px 0;"
    "}"
    ".qs-card {"
    "  background-color: @card_bg_color;"
    "  border: 1px solid alpha(@window_fg_color, 0.1);"
    "  border-radius: 12px;"
    "  padding: 16px;"
    "}"
    ".qs-hairline {"
    "  border-bottom: 1px solid alpha(@window_fg_color, 0.05);"
    "}"
    ".qs-recent-empty {"
    "  padding: 48px 24px;"
    "  background-color: alpha(@window_fg_color, 0.02);"
    "  border-radius: 12px;"
    "  border: 1px dashed alpha(@window_fg_color, 0.1);"
    "}"
    ".title-1 {"
    "  font-weight: 800;"
    "  font-size: 24pt;"
    "  letter-spacing: 0;"
    "}"
    ".title-2 {"
    "  font-weight: 700;"
    "  font-size: 18pt;"
    "}"
    ".dim-label {"
    "  color: alpha(@window_fg_color, 0.55);"
    "}"
    ".bold {"
    "  font-weight: 700;"
    "}"
    ".caption {"
    "  font-size: 10pt;"
    "}"
    "button.pill {"
    "  border-radius: 9999px;"
    "  padding-left: 24px;"
    "  padding-right: 24px;"
    "}"
    "progressbarra trough {"
    "  min-height: 6px;"
    "  border-radius: 3px;"
    "}"
    "progressbarra progress {"
    "  border-radius: 3px;"
    "  background-color: @accent_color;"
    "}";

void qs_app_install_css(void) {
  GtkCssProvider* provider = gtk_css_provider_new();
  gtk_css_provider_load_from_string(provider, QS_CSS);
  gtk_style_context_add_provider_for_display(
      gdk_display_get_default(),
      GTK_STYLE_PROVIDER(provider),
      GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
  g_object_unref(provider);
}
