#include "style.h"

#include <gtk/gtk.h>

static const char QS_CSS[] =
    "@keyframes qs-fade-in {"
    "  from { opacity: 0; }"
    "  to   { opacity: 1; }"
    "}"
    "@keyframes qs-float {"
    "  0% { transform: translateY(0px); }"
    "  50% { transform: translateY(-10px); }"
    "  100% { transform: translateY(0px); }"
    "}"
    "@keyframes qs-pulse-border {"
    "  0% { border-color: alpha(@window_fg_color, 0.1); }"
    "  50% { border-color: @accent_color; }"
    "  100% { border-color: alpha(@window_fg_color, 0.1); }"
    "}"
    "@keyframes qs-pulse-glow {"
    "  0% { box-shadow: 0 0 0 0 rgba(46, 194, 126, 0.4); }"
    "  70% { box-shadow: 0 0 0 6px rgba(46, 194, 126, 0); }"
    "  100% { box-shadow: 0 0 0 0 rgba(46, 194, 126, 0); }"
    "}"
    ".qs-home-layout {"
    "  background-color: @window_bg_color;"
    "}"
    ".qs-home-left {"
    "  background-color: alpha(@window_fg_color, 0.02);"
    "}"
    ".qs-status-dot {"
    "  min-width: 8px;"
    "  min-height: 8px;"
    "  border-radius: 99px;"
    "  margin-right: 8px;"
    "}"
    ".qs-status-dot.online {"
    "  background-color: #2ec27e;"
    "  animation: qs-pulse-glow 2s infinite ease-in-out;"
    "}"
    ".qs-status-dot.offline { background-color: alpha(@window_fg_color, 0.3); }"
    ".qs-status-toggle {"
    "  background: transparent;"
    "  border-radius: 8px;"
    "  padding: 6px 10px;"
    "  min-height: 0;"
    "  transition: background-color 150ms ease;"
    "}"
    ".qs-status-toggle:hover {"
    "  background-color: alpha(@window_fg_color, 0.06);"
    "}"
    ".qs-status-toggle:active {"
    "  background-color: alpha(@window_fg_color, 0.10);"
    "}"
    ".qs-status-chevron {"
    "  transition: transform 150ms ease;"
    "}"
    ".qs-status-toggle:hover .qs-status-chevron {"
    "  transform: translateX(2px);"
    "}"
    ".qs-link-button {"
    "  color: @accent_color;"
    "  font-weight: 700;"
    "  padding: 0;"
    "}"
    ".qs-drop-zone {"
    "  border: 2px dashed alpha(@window_fg_color, 0.1);"
    "  border-radius: 54px;"
    "  padding: 60px;"
    "  background-color: alpha(@window_fg_color, 0.01);"
    "  transition: all 400ms cubic-bezier(0.25, 0.46, 0.45, 0.94);"
    "}"
    ".qs-drop-zone:hover {"
    "  border-color: @accent_color;"
    "  background-color: alpha(@accent_color, 0.05);"
    "  transform: scale(1.02);"
    "}"
    ".qs-logo-float {"
    "  animation: qs-float 4s infinite ease-in-out;"
    "}"
    ".qs-splash-container {"
    "  animation: qs-fade-in 600ms ease-out;"
    "  padding: 48px;"
    "}"
    ".qs-splash-icon {"
    "  margin-bottom: 8px;"
    "}"
    ".qs-splash-loader {"
    "  margin-top: 32px;"
    "}"
    ".qs-hero-icon {"
    "  margin-top: 8px;"
    "  margin-bottom: 12px;"
    "  color: alpha(@window_fg_color, 0.7);"
    "}"
    ".qs-hero-block {"
    "  margin-bottom: 12px;"
    "  padding: 32px 0;"
    "}"
    ".qs-card {"
    "  background-color: @card_bg_color;"
    "  border: 1px solid alpha(@window_fg_color, 0.1);"
    "  border-radius: 12px;"
    "  padding: 16px;"
    "}"
    ".qs-hairline {"
    "  border-bottom: 1px solid alpha(@window_fg_color, 0.05);"
    "}"
    ".qs-recent-empty {"
    "  padding: 48px 24px;"
    "  background-color: alpha(@window_fg_color, 0.02);"
    "  border-radius: 12px;"
    "  border: 1px dashed alpha(@window_fg_color, 0.1);"
    "}"
    ".title-1 {"
    "  font-weight: 800;"
    "  font-size: 24pt;"
    "  letter-spacing: 0;"
    "}"
    ".title-2 {"
    "  font-weight: 700;"
    "  font-size: 18pt;"
    "}"
    ".dim-label {"
    "  color: alpha(@window_fg_color, 0.55);"
    "}"
    ".bold {"
    "  font-weight: 700;"
    "}"
    ".caption {"
    "  font-size: 10pt;"
    "}"
    "button.pill {"
    "  border-radius: 9999px;"
    "  padding-left: 24px;"
    "  padding-right: 24px;"
    "}"
    "progressbarra trough {"
    "  min-height: 6px;"
    "  border-radius: 3px;"
    "}"
    "progressbarra progress {"
    "  border-radius: 3px;"
    "  background-color: @accent_color;"
    "}"
    ".qs-visibility-options-box {"
    "  background-color: alpha(@window_fg_color, 0.03);"
    "  border: 1px solid alpha(@window_fg_color, 0.08);"
    "  border-radius: 12px;"
    "  padding: 8px;"
    "  margin-top: 6px;"
    "  margin-bottom: 6px;"
    "}"
    ".qs-visibility-option {"
    "  padding: 10px 12px;"
    "  border-radius: 8px;"
    "  margin-bottom: 4px;"
    "  min-height: 0;"
    "  transition: background-color 150ms ease;"
    "}"
    ".qs-visibility-option:hover {"
    "  background-color: alpha(@window_fg_color, 0.05);"
    "}"
    ".qs-visibility-option:active {"
    "  background-color: alpha(@window_fg_color, 0.08);"
    "}"
    ".qs-visibility-option-icon {"
    "  color: @accent_color;"
    "  margin-right: 12px;"
    "}"
    ".qs-icon-blue { color: #3584e4; }"
    ".qs-icon-green { color: #2ec27e; }"
    ".qs-icon-orange { color: #e66100; }"
    ".qs-icon-violet { color: #9141ac; }"
    ".qs-icon-yellow { color: #f6d32d; }"
    ".qs-icon-teal { color: #16a085; }"
    ".qs-icon-pink { color: #e21c60; }"
    ".qs-settings-back-btn { color: @accent_color; }"
    ".qs-settings-title {"
    "  font-family: 'Outfit', 'Inter', 'Roboto', sans-serif;"
    "  font-size: 24pt;"
    "  font-weight: 500;"
    "  letter-spacing: -0.5px;"
    "  color: @window_fg_color;"
    "}"
    ".qs-warning-banner {"
    "  background-color: alpha(#e66100, 0.06);"
    "  border: 1px solid alpha(#e66100, 0.15);"
    "  border-radius: 99px;"
    "  padding: 6px 16px;"
    "  box-shadow: 0 4px 12px alpha(#000000, 0.03);"
    "  transition: all 300ms ease;"
    "}"
    ".qs-warning-banner:hover {"
    "  background-color: alpha(#e66100, 0.10);"
    "  border-color: alpha(#e66100, 0.25);"
    "  transform: translateY(-1px);"
    "}"
    ".qs-warning-banner-text {"
    "  font-size: 10pt;"
    "  font-weight: 500;"
    "  color: #e66100;"
    "  margin-left: 6px;"
    "}"
    ".qs-warning-banner-btn {"
    "  color: #ffffff;"
    "  font-weight: 700;"
    "  font-size: 9.5pt;"
    "  padding: 4px 12px;"
    "  border-radius: 99px;"
    "  background-color: #e66100;"
    "  border: none;"
    "  transition: background-color 150ms ease;"
    "}"
    ".qs-warning-banner-btn:hover {"
    "  background-color: #d55600;"
    "}"
    ".qs-logo-float {"
    "  animation: qs-float 5s infinite ease-in-out;"
    "}"
    ".qs-drop-zone {"
    "  border: 1.5px dashed alpha(@accent_color, 0.3);"
    "  border-radius: 24px;"
    "  padding: 48px;"
    "  background-color: alpha(@window_fg_color, 0.015);"
    "  box-shadow: inset 0 2px 8px alpha(#000000, 0.02);"
    "  transition: all 350ms cubic-bezier(0.16, 1, 0.3, 1);"
    "}"
    ".qs-drop-zone:hover {"
    "  border-color: @accent_color;"
    "  border-style: solid;"
    "  background-color: alpha(@accent_color, 0.03);"
    "  box-shadow: 0 12px 32px alpha(@accent_color, 0.08), inset 0 2px 8px alpha(#000000, 0.01);"
    "  transform: translateY(-4px);"
    "}"
    ".qs-drop-zone-icon {"
    "  color: @accent_color;"
    "  transition: all 350ms cubic-bezier(0.16, 1, 0.3, 1);"
    "}"
    ".qs-drop-zone:hover .qs-drop-zone-icon {"
    "  transform: scale(1.15) translateY(-4px);"
    "}"
    ".qs-drop-zone-text {"
    "  font-size: 11pt;"
    "  font-weight: 500;"
    "  color: alpha(@window_fg_color, 0.6);"
    "  letter-spacing: -0.2px;"
    "}"
    ".qs-scanner-container {"
    "  background-color: alpha(@window_fg_color, 0.02);"
    "  border: 1px solid alpha(@window_fg_color, 0.08);"
    "  border-radius: 20px;"
    "  padding: 24px;"
    "  box-shadow: 0 8px 24px alpha(#000000, 0.03);"
    "  transition: all 300ms ease;"
    "}"
    ".qs-scanner-header {"
    "  margin-bottom: 16px;"
    "}"
    ".qs-scanner-title {"
    "  font-size: 12pt;"
    "  font-weight: 600;"
    "  letter-spacing: -0.3px;"
    "  color: @window_fg_color;"
    "}"
    ".qs-scanner-device-row {"
    "  border-radius: 10px;"
    "  margin-bottom: 6px;"
    "  border: 1px solid transparent;"
    "  transition: all 150ms ease;"
    "}"
    ".qs-scanner-device-row:hover {"
    "  background-color: alpha(@accent_color, 0.08);"
    "  border-color: alpha(@accent_color, 0.2);"
    "  transform: translateX(4px);"
    "}";

void qs_app_install_css(void) {
  GtkCssProvider* provider = gtk_css_provider_new();
  gtk_css_provider_load_from_string(provider, QS_CSS);
  gtk_style_context_add_provider_for_display(
      gdk_display_get_default(),
      GTK_STYLE_PROVIDER(provider),
      GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
  g_object_unref(provider);
}
